### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by cscherrer** [scheinerman/SimpleWorld.jl#1]
Hi Ed,

I'm working on a conference submission for [Soss.jl](https://github.com/cscherrer/Soss.jl), which uses SimplePosets and SimpleGraphs. I'd love to be able to cite these packages. Do you know a way I could do this?

**Comment by scheinerman** [comment]
First: Thanks for letting me know and I'm glad you're finding these packages useful. And to your question, I don't know but if I had to guess, something like this:

Scheinerman, Edward. SimpleGraphs Julia module, github.com/scheinerman/SimpleGraphs.jl 

I use BibTeX and something like this would be what I'd do:

```
@Misc{SimpleGraphs,
  key = 	 {SimpleGraphs},
  author = 	 {Edward Scheinerman},
  title = 	 {\texttt{SimpleGraphs} {J}ulia module},
  howpublished = {\url{github.com/scheinerman/SimpleGraphs.jl}}
}
```

You'll need `\usepackage{url}` in your LaTeX header.

I hope this helps.

**Comment by cscherrer** [comment]
That's great, thank you!
